using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mensageria.Models
{
    public class Account
    {
        public string accountcategorycode { get; set; }
        public string accountclassificationcode { get; set; }
        public string accountid { get; set; }
        public string accountnumber { get; set; }
        public string accountratingcode { get; set; }
        public string address1_addressid { get; set; }
        public string address1_addresstypecode { get; set; }
        public string address1_city { get; set; }
        public string address1_composite { get; set; }
        public string address1_country { get; set; }
        public string address1_county { get; set; }
        public string address1_fax { get; set; }
        public string address1_freighttermscode { get; set; }
        public string address1_latitude { get; set; }
        public string address1_line1 { get; set; }
        public string address1_line2 { get; set; }
        public string address1_line3 { get; set; }
        public string address1_longitude { get; set; }
        public string address1_name { get; set; }
        public string address1_postalcode { get; set; }
        public string address1_postofficebox { get; set; }
        public string address1_primarycontactname { get; set; }
        public string address1_shippingmethodcode { get; set; }
        public string address1_stateorprovince { get; set; }
        public string address1_telephone1 { get; set; }
        public string address1_telephone2 { get; set; }
        public string address1_telephone3 { get; set; }
        public string address1_upszone { get; set; }
        public string address1_utcoffset { get; set; }
        public string address2_addressid { get; set; }
        public string address2_addresstypecode { get; set; }
        public string address2_city { get; set; }
        public string address2_composite { get; set; }
        public string address2_country { get; set; }
        public string address2_county { get; set; }
        public string address2_fax { get; set; }
        public string address2_freighttermscode { get; set; }
        public string address2_latitude { get; set; }
        public string address2_line1 { get; set; }
        public string address2_line2 { get; set; }
        public string address2_line3 { get; set; }
        public string address2_longitude { get; set; }
        public string address2_name { get; set; }
        public string address2_postalcode { get; set; }
        public string address2_postofficebox { get; set; }
        public string address2_primarycontactname { get; set; }
        public string address2_shippingmethodcode { get; set; }
        public string address2_stateorprovince { get; set; }
        public string address2_telephone1 { get; set; }
        public string address2_telephone2 { get; set; }
        public string address2_telephone3 { get; set; }
        public string address2_upszone { get; set; }
        public string address2_utcoffset { get; set; }
        public string aging30 { get; set; }
        public string aging30_base { get; set; }
        public string aging60 { get; set; }
        public string aging60_base { get; set; }
        public string aging90 { get; set; }
        public string aging90_base { get; set; }
        public string businesstypecode { get; set; }
        public string createdby { get; set; }
        public string createdon { get; set; }
        public string createdonbehalfby { get; set; }
        public string creditlimit { get; set; }
        public string creditlimit_base { get; set; }
        public string creditonhold { get; set; }
        public string customersizecode { get; set; }
        public string customertypecode { get; set; }
        public string defaultpricelevelid { get; set; }
        public string description { get; set; }
        public string donotbulkemail { get; set; }
        public string donotbulkpostalmail { get; set; }
        public string donotemail { get; set; }
        public string donotfax { get; set; }
        public string donotphone { get; set; }
        public string donotpostalmail { get; set; }
        public string donotsendmm { get; set; }
        public string emailaddress1 { get; set; }
        public string emailaddress2 { get; set; }
        public string emailaddress3 { get; set; }
        public string entityimage { get; set; }
        public string exchangerate { get; set; }
        public string fax { get; set; }
        public string ftpsiteurl { get; set; }
        public string i9_aliquota { get; set; }
        public string i9_bloquear_atendimento_cliente { get; set; }
        public string i9_bloquear_conta { get; set; }
        public string i9_bloqueia_licenca_uso_cliente { get; set; }
        public string i9_celular_aux { get; set; }
        public string i9_cidade { get; set; }
        public string i9_cliente_pagador { get; set; }
        public string i9_cliente_pagador_centraliza_hrs { get; set; }
        public string i9_cobranca_impressa { get; set; }
        public string i9_cofins { get; set; }
        public string i9_conta_contabil { get; set; }
        public string i9_cpf_cnpj { get; set; }
        public string i9_cpf_cnpj_aux { get; set; }
        public string i9_csll { get; set; }
        public string i9_ddd_celular { get; set; }
        public string i9_ddd_fax { get; set; }
        public string i9_dddfone2 { get; set; }
        public string i9_documento_estrangeiro { get; set; }
        public string i9_estado { get; set; }
        public string i9_etiqueta { get; set; }
        public string i9_exterior { get; set; }
        public string i9_fax_aux { get; set; }
        public string i9_gerar_nf_automatica { get; set; }
        public string i9_grupo { get; set; }
        public string i9_indicador_inscricao_estadual_destinatario { get; set; }
        public string i9_inscricao_estadual { get; set; }
        public string i9_inscricao_municipal { get; set; }
        public string i9_irrf { get; set; }
        public string i9_isento_inscricao { get; set; }
        public string i9_nao_cobra_atendimento_telefonico { get; set; }
        public string i9_nome_fantasia { get; set; }
        public string i9_observacao { get; set; }
        public string i9_observacao_atendimento { get; set; }
        public string i9_pais { get; set; }
        public string i9_pis { get; set; }
        public string i9_receita { get; set; }
        public string i9_retem_inss { get; set; }
        public string i9_retem_iss { get; set; }
        public string i9_rg { get; set; }
        public string i9_telephone1_aux { get; set; }
        public string i9_transportadora { get; set; }
        public string i9_utilizar_rg_como_cnpj { get; set; }
        public string importsequencenumber { get; set; }
        public string industrycode { get; set; }
        public string lastusedincampaign { get; set; }
        public string marketcap { get; set; }
        public string marketcap_base { get; set; }
        public string masterid { get; set; }
        public string merged { get; set; }
        public string modifiedby { get; set; }
        public string modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string name { get; set; }
        public string new_cli_pagador { get; set; }
        public string new_contato { get; set; }
        public string new_contatoid { get; set; }
        public string new_pai_codigo { get; set; }
        public string new_pk_codigo { get; set; }
        public string new_pk_emp_codigo { get; set; }
        public string new_representante_codigo { get; set; }
        public string new_telefonecomercial { get; set; }
        public string numberofemployees { get; set; }
        public string opendeals { get; set; }
        public string openrevenue { get; set; }
        public string openrevenue_base { get; set; }
        public string originatingleadid { get; set; }
        public string overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string ownershipcode { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public string parentaccountid { get; set; }
        public string participatesinworkflow { get; set; }
        public string paymenttermscode { get; set; }
        public string preferredappointmentdaycode { get; set; }
        public string preferredappointmenttimecode { get; set; }
        public string preferredcontactmethodcode { get; set; }
        public string preferredequipmentid { get; set; }
        public string preferredserviceid { get; set; }
        public string preferredsystemuserid { get; set; }
        public string primarycontactid { get; set; }
        public string processid { get; set; }
        public string revenue { get; set; }
        public string revenue_base { get; set; }
        public string sharesoutstanding { get; set; }
        public string shippingmethodcode { get; set; }
        public string sic { get; set; }
        public string stageid { get; set; }
        public string statecode { get; set; }
        public string statuscode { get; set; }
        public string stockexchange { get; set; }
        public string telephone1 { get; set; }
        public string telephone2 { get; set; }
        public string telephone3 { get; set; }
        public string territorycode { get; set; }
        public string territoryid { get; set; }
        public string tickersymbol { get; set; }
        public string timezoneruleversionnumber { get; set; }
        public string transactioncurrencyid { get; set; }
        public string traversedpath { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public string versionnumber { get; set; }
        public string websiteurl { get; set; }
        public string yominame { get; set; }
    }
}