using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mensageria.Models
{
    public class Opportunity
    {
        public string test { get; set; }
        public string actualclosedate { get; set; }
        public string actualvalue { get; set; }
        public string actualvalue_base { get; set; }
        public string budgetamount { get; set; }
        public string budgetamount_base { get; set; }
        public string budgetstatus { get; set; }
        public string campaignid { get; set; }
        public string captureproposalfeedback { get; set; }
        public string closeprobability { get; set; }
        public string completefinalproposal { get; set; }
        public string completeinternalreview { get; set; }
        public string confirminterest { get; set; }
        public string createdby { get; set; }
        public string createdon { get; set; }
        public string createdonbehalfby { get; set; }
        public string currentsituation { get; set; }
        public string customerid { get; set; }
        public string customerneed { get; set; }
        public string customerpainpoints { get; set; }
        public string decisionmaker { get; set; }
        public string description { get; set; }
        public string developproposal { get; set; }
        public string discountamount { get; set; }
        public string discountamount_base { get; set; }
        public string discountpercentage { get; set; }
        public string estimatedclosedate { get; set; }
        public string estimatedvalue { get; set; }
        public string estimatedvalue_base { get; set; }
        public string evaluatefit { get; set; }
        public string exchangerate { get; set; }
        public string filedebrief { get; set; }
        public string finaldecisiondate { get; set; }
        public string freightamount { get; set; }
        public string freightamount_base { get; set; }
        public string i9_antecipo_minuta_contrato { get; set; }
        public string i9_case_sucesso { get; set; }
        public string i9_descricao_pgto_adesao { get; set; }
        public string i9_descricao_pgto_ass_usuario { get; set; }
        public string i9_descricao_pgto_atualizacao { get; set; }
        public string i9_descricao_pgto_customizacao { get; set; }
        public string i9_descricao_pgto_implantacao { get; set; }
        public string i9_descricao_pgto_manutencao { get; set; }
        public string i9_descricao_pgto_venda { get; set; }
        public string i9_forma_pgto_adesao { get; set; }
        public string i9_forma_pgto_ass_por_usuario { get; set; }
        public string i9_forma_pgto_atualizacao { get; set; }
        public string i9_forma_pgto_customizacao { get; set; }
        public string i9_forma_pgto_implantacao { get; set; }
        public string i9_forma_pgto_manutencao { get; set; }
        public string i9_forma_pgto_venda { get; set; }
        public string i9_gerente_desconto { get; set; }
        public string i9_ligacao_feita { get; set; }
        public string i9_origem { get; set; }
        public string i9_origem_do_cliente { get; set; }
        public string i9_patrocinadores_decisores { get; set; }
        public string i9_pesquiso_site_empresa { get; set; }
        public string i9_regiao { get; set; }
        public string i9_retirou_duvidas_aderencia_software { get; set; }
        public string i9_reuniao_decisores { get; set; }
        public string i9_segmento_compativel { get; set; }
        public string i9_segunda_reuniao { get; set; }
        public string i9_solicitacao_desconto { get; set; }
        public string i9_tabela_preco { get; set; }
        public string i9_tempo_medio_abertura { get; set; }
        public string i9_tempodefalha { get; set; }
        public string i9_testandosoma { get; set; }
        public string i9_unidade_negocio { get; set; }
        public string i9_vice_presidente_desconto { get; set; }
        public string i9_visita_agendada { get; set; }
        public string identifycompetitors { get; set; }
        public string identifycustomercontacts { get; set; }
        public string identifypursuitteam { get; set; }
        public string importsequencenumber { get; set; }
        public string initialcommunication { get; set; }
        public string isrevenuesystemcalculated { get; set; }
        public string modifiedby { get; set; }
        public string modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string name { get; set; }
        public string need { get; set; }
        public string new_cessodedireitodeusocdu { get; set; }
        public string new_cronograma_ajustado { get; set; }
        public string new_descrioparaimplantao { get; set; }
        public string new_parceiro { get; set; }
        public string opportunityid { get; set; }
        public string opportunityratingcode { get; set; }
        public string originatingleadid { get; set; }
        public string overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public string parentaccountid { get; set; }
        public string parentcontactid { get; set; }
        public string participatesinworkflow { get; set; }
        public string presentfinalproposal { get; set; }
        public string processid { get; set; }
        public string proposedsolution { get; set; }
        public string purchaseprocess { get; set; }
        public string purchasetimeframe { get; set; }
        public string pursuitdecision { get; set; }
        public string qualificationcomments { get; set; }
        public string quotecomments { get; set; }
        public string resolvefeedback { get; set; }
        public string salesstage { get; set; }
        public string salesstagecode { get; set; }
        public string schedulefollowup_prospect { get; set; }
        public string schedulefollowup_qualify { get; set; }
        public string scheduleproposalmeeting { get; set; }
        public string sendthankyounote { get; set; }
        public string stageid { get; set; }
        public string statecode { get; set; }
        public string statuscode { get; set; }
        public string stepid { get; set; }
        public string stepname { get; set; }
        public string timeline { get; set; }
        public string timezoneruleversionnumber { get; set; }
        public string totalamount { get; set; }
        public string totalamount_base { get; set; }
        public string totalamountlessfreight { get; set; }
        public string totalamountlessfreight_base { get; set; }
        public string totaldiscountamount { get; set; }
        public string totaldiscountamount_base { get; set; }
        public string totallineitemamount { get; set; }
        public string totallineitemamount_base { get; set; }
        public string totallineitemdiscountamount { get; set; }
        public string totallineitemdiscountamount_base { get; set; }
        public string totaltax { get; set; }
        public string totaltax_base { get; set; }
        public string transactioncurrencyid { get; set; }
        public string traversedpath { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public string versionnumber { get; set; }
    }
}