using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mensageria.Models
{
    public class ProductOpportunity
    {
        public string baseamount { get; set; }
        public string baseamount_base { get; set; }
        public string createdby { get; set; }
        public string createdon { get; set; }
        public string createdonbehalfby { get; set; }
        public string description { get; set; }
        public string entityimage { get; set; }
        public string exchangerate { get; set; }
        public string extendedamount { get; set; }
        public string extendedamount_base { get; set; }
        public string i9_autoriaza_doacao { get; set; }
        public string i9_aux_calculo_produto { get; set; }
        public string i9_avaliacao_desempenho { get; set; }
        public string i9_cargos_salarios { get; set; }
        public string i9_conceder_desconto { get; set; }
        public string i9_desconto { get; set; }
        public string i9_desconto1 { get; set; }
        public string i9_desconto2 { get; set; }
        public string i9_desconto3 { get; set; }
        public string i9_desconto4 { get; set; }
        public string i9_descricao_solicitacao { get; set; }
        public string i9_diretor { get; set; }
        public string i9_gerente { get; set; }
        public string i9_gerente_comercial { get; set; }
        public string i9_horas_franquia { get; set; }
        public string i9_lista_preco { get; set; }
        public string i9_modalidade1 { get; set; }
        public string i9_modalidade2 { get; set; }
        public string i9_modalidade3 { get; set; }
        public string i9_modalidade4 { get; set; }
        public string i9_modulo { get; set; }
        public string i9_perfil { get; set; }
        public string i9_pesquisa { get; set; }
        public string i9_porc_aumento_1 { get; set; }
        public string i9_porc_aumento_2 { get; set; }
        public string i9_porc_aumento_3 { get; set; }
        public string i9_porc_aumento_4 { get; set; }
        public string i9_porc_max_desconto { get; set; }
        public string i9_porcentagem_desconto { get; set; }
        public string i9_qtd_funcionario { get; set; }
        public string i9_qtd_modalidade1 { get; set; }
        public string i9_qtd_modalidade2 { get; set; }
        public string i9_qtd_modalidade3 { get; set; }
        public string i9_qtd_modalidade4 { get; set; }
        public string i9_qtd_modulos { get; set; }
        public string i9_qtd_usuario { get; set; }
        public string i9_recrut_selecao { get; set; }
        public string i9_sesmt { get; set; }
        public string i9_tab_ajuste_func_1 { get; set; }
        public string i9_tab_ajuste_func_2 { get; set; }
        public string i9_tab_ajuste_func_3 { get; set; }
        public string i9_tab_ajuste_func_4 { get; set; }
        public string i9_tab_ajuste_usuario_1 { get; set; }
        public string i9_tab_ajuste_usuario_2 { get; set; }
        public string i9_tab_ajuste_usuario_3 { get; set; }
        public string i9_tab_ajuste_usuario_4 { get; set; }
        public string i9_tabela_preco { get; set; }
        public string i9_trein_desenvolvimento { get; set; }
        public string i9_unidade_negocio { get; set; }
        public string i9_valor_com_desconto1 { get; set; }
        public string i9_valor_com_desconto1_base { get; set; }
        public string i9_valor_com_desconto2 { get; set; }
        public string i9_valor_com_desconto2_base { get; set; }
        public string i9_valor_com_desconto3 { get; set; }
        public string i9_valor_com_desconto3_base { get; set; }
        public string i9_valor_com_desconto4 { get; set; }
        public string i9_valor_com_desconto4_base { get; set; }
        public string i9_valor1 { get; set; }
        public string i9_valor1_base { get; set; }
        public string i9_valor2 { get; set; }
        public string i9_valor2_base { get; set; }
        public string i9_valor3 { get; set; }
        public string i9_valor3_base { get; set; }
        public string i9_valor4 { get; set; }
        public string i9_valor4_base { get; set; }
        public string i9_visualizar_ajustes { get; set; }
        public string importsequencenumber { get; set; }
        public string ispriceoverridden { get; set; }
        public string isproductoverridden { get; set; }
        public string lineitemnumber { get; set; }
        public string manualdiscountamount { get; set; }
        public string manualdiscountamount_base { get; set; }
        public string modifiedby { get; set; }
        public string modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string new_produtodaoportunidadeid { get; set; }
        public string opportunityid { get; set; }
        public string opportunityproductid { get; set; }
        public string opportunitystatecode { get; set; }
        public string overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string owningbusinessunit { get; set; }
        public string owninguser { get; set; }
        public string parentbundleid { get; set; }
        public string priceperunit { get; set; }
        public string priceperunit_base { get; set; }
        public string pricingerrorcode { get; set; }
        public string productassociationid { get; set; }
        public string productdescription { get; set; }
        public string productid { get; set; }
        public string producttypecode { get; set; }
        public string propertyconfigurationstatus { get; set; }
        public string quantity { get; set; }
        public string sequencenumber { get; set; }
        public string tax { get; set; }
        public string tax_base { get; set; }
        public string timezoneruleversionnumber { get; set; }
        public string transactioncurrencyid { get; set; }
        public string uomid { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public string versionnumber { get; set; }
        public string volumediscountamount { get; set; }
        public string volumediscountamount_base { get; set; }
    }
}